### ISSUE TITLE
could you share the fbx model

### ISSUE THREAD

**Issue by bigpo** [ubisoft/ubisoft-laforge-ZeroEGGS#1]
hi， thanks for sharing the excellent work.  I want to visualize the animation on unity platform but lack of the fbx model, could you share it? Thanks!

**Comment by ChenWang8750** [comment]
Excellent job!

But could you please share the fbx model corresponding to the dataset? OR how to visualize this data?

Thanks!

**Comment by saeed1262** [comment]
Hi @bigpo, we are looking into it (in terms of licensing the FBX model). Please stay tuned.

**Comment by cjerry1243** [comment]
Looking forward to it!

**Comment by nagyrajmund** [comment]
Hey-hey, just wondering, are there any updates regarding the FBX model? :)

**Comment by saeed1262** [comment]
@nagyrajmund Not yet, unfortunately. We are still looking into it.
