### ISSUE TITLE
nan error 

### ISSUE THREAD

**Issue by puppet101** [ubisoft/ubisoft-laforge-ZeroEGGS#12]
Hi, thanks for sharing this code!  I download the dataset and pretrained model, but when I run the inference code following your instructions, the output bvh file is wrong. All of the output is nan from frame 2, the command I use is 

python ./generate.py -o "../data/outputs/v1/options.json" -s "../data/Zeggs_data/clean/065_Speech_0_x_1_0.bvh" -a "../data/Zeggs_data/clean/065_Speech_0_x_1_0.wav"

Could you please give me some instructions? Thank you !

**Comment by saeed1262** [comment]
Hi,
Unfortunately, I cannot reproduce the issue. Just ran the same command and got the correct results.

**Comment by puppet101** [comment]
I have solved it, thank you!  The reason is that my dataset is not processed correctly.

**Comment by zll961020** [comment]
Hi, I also met "nan" when inference with audio_config.centered=False or audio_config.normalize_loudness=False, could you please explain what causes this?
