### ISSUE TITLE
Unable to generate required files for inference using data_pipeline.py

### ISSUE THREAD

**Issue by anooj-gandham** [ubisoft/ubisoft-laforge-ZeroEGGS#13]
Hi

When I run  `python data_pipeline.py` the process did not finish and it is getting killed.

Screenshot:
![image](https://user-images.githubusercontent.com/63911217/204796852-dd7dd526-c755-4922-be99-c8e99cdbcae2.png)

Enviroment:
![image](https://user-images.githubusercontent.com/63911217/204797183-155f7fe5-b79a-452f-938b-ab6ea0311017.png)

How do I run this process successfully?
Any help would be appreciated.
Thanks in advance.

**Comment by anooj-gandham** [comment]
Hi @saeed1262 
Thanks for responding.

My machine has a 30GB RAM and running only this process.

**Comment by saeed1262** [comment]
Hi,
Unfortunately, I cannot reproduce this on my end. I would run it in debug mode and check where it is killed.

**Comment by anooj-gandham** [comment]
Thanks, for now I have used the processed files generated previously in another machine. It is working well.
