### ISSUE TITLE
batch response: This repository is over its data quota

### ISSUE THREAD

**Issue by youngstu** [ubisoft/ubisoft-laforge-ZeroEGGS#20]
```
Git LFS: (0 of 3 files) 0 B / 2.58 GB                                                                                                                                                
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/ubisoft/ubisoft-laforge-ZeroEGGS.git/info/lfs'

```

Download failed. Could you upload dataset to Google Cloud Disk. Very thanks.

**Comment by youngstu** [comment]
![Screenshot from 2023-01-10 15-44-49](https://user-images.githubusercontent.com/26452514/211491479-d8c323e0-4564-4463-ab22-844b4eb56bdb.png)

**Comment by saeed1262** [comment]
Working on it. Please stay tuned.

**Comment by youngstu** [comment]
Maybe the quota of your LFS account has exceeded the limit. Now other people can't download data. Could you upload it to Google Cloud Disk which is more convenient to download. 

Very thanks.

**Comment by saeed1262** [comment]
It will be solved hopefully soon. Unfortunately, we cannot put it on Google Cloud due to licensing

**Comment by youngstu** [comment]
The work is excellent, but since there is no data to test the actual effect, when could it be solved. Thanks.

**Comment by saeed1262** [comment]
Solved. Please try again.

**Comment by youngstu** [comment]
> Solved. Please try again.

It's solved, very thanks.

**Comment by 2lmlzr** [comment]
I'm also experiencing the same LFS quota issue. 
Has anyone found a working alternative download link for the dataset? 
Any help would be appreciated.
