### ISSUE TITLE
The Zeggs_data.zip file occur error when I try to unzip it.

### ISSUE THREAD

**Issue by LaolangOne** [ubisoft/ubisoft-laforge-ZeroEGGS#3]

**Comment by saeed1262** [comment]
Hi, 
It's been tested with WinZip and WinRAR and works. Should also work with 7-Zip.

**Comment by LaolangOne** [comment]
> Hi, It's been tested with WinZip and WinRAR and works. Should also work with 7-Zip.

I have tried these methods,it still occur many error.In the win10,some unziped files is 0 KB and Ubuntu directly unzip will occur error "not an archive".Maybe you should download the Zeggs_data.zip file to unzip it to analy the error.

**Comment by youngstu** [comment]
> Hi, It's been tested with WinZip and WinRAR and works. Should also work with 7-Zip.

The lfs cannot work, the dataset no way to download.

**Comment by youngstu** [comment]
![Screenshot from 2023-01-10 15-44-49](https://user-images.githubusercontent.com/26452514/211491593-451b1c96-0ec7-4664-b1b4-6321d7d7e967.png)

**Comment by saeed1262** [comment]
Hi,
We are working on it. Please stay tuned.

**Comment by Vahe987** [comment]
I still have the error, the Zeggs_data.zip file is impossible to unzip, so many error, looks corrupted.
Tried to copy files inside, manually, no luck.
Tried on Windows 11 and Ubuntu 22
