### ISSUE TITLE
How can I run GPU instead of CPU?

### ISSUE THREAD

**Issue by BunyaminEfe** [ubisoft/ubisoft-laforge-ZeroEGGS#4]
Using CPU!
|     0 |     62 | [                              ]   0.10% |   0.6580 | 11:25:51 | 

The process is taking too long, is there a solution for it to run it with a video card?

**Comment by saeed1262** [comment]
Hi. You need a GPU and installed NVidia drivers and CUDA libraries installed

**Comment by BunyaminEfe** [comment]
It shows as GPU on CMD screen but uses RAM in task manager.  Is there any solution about this?
